### ISSUE TITLE
Fix your shit please

### ISSUE THREAD

**Issue by xbHA16ha11y** [RosneBurgerworks/cathook#1]
1 - Why would you remove literally everything?
2 - the second i inject and join a game, it crashes.

2/10. Atleast compiles for ubuntu. not like bencat's stupid mistakes.

**Comment by rosne-gamingyt** [comment]
First of all, our fork for some reason doesn't show some tabs. But, if you take a look at the code, you can see that they are still there. And for your other issue, i'll start get working soon.

**Comment by xbHA16ha11y** [comment]
okay mate.
